<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>ByensGaader.Api</RootNamespace>
    <UserSecretsId>byensgaader-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FastEndpoints.Swagger" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ByensGaader.Api.Tests" />
  </ItemGroup>
</Project>
